[book]
authors = ["peter"]
language = "cn"
multilingual = false
src = "src"
title = "Polos MCU开发板使用指南"


[output.html]
destination = "../docs/polos"
sidebar = true  # 关键配置：强制显示侧边栏（禁用自动隐藏）
site-url = "/polos/"